/**
 * `refactor_remove_unused` — emit a removal shell script for resources
 * with zero inbound refs (L5-6, dry-run only).
 *
 * High data-loss risk if the LLM gets this wrong, so v1 is DRY-RUN
 * ONLY — the tool emits an executable `rm` / `del` script that the
 * human runs by hand after review. Live-delete deferred to L10.
 *
 * Composes with `find_unused_resources` (L2-4) under the hood; this
 * tool's value is producing a copy-paste-ready cleanup script with
 * preflight context (file count, total bytes, safety reminders).
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { existsSync, statSync } from "node:fs";
import { resolve } from "node:path";
import { z } from "zod";
import type { ProjectIndex } from "../project-index/project-index.js";
import type { ResourceSource } from "../project-index/types.js";

interface RemovalCandidate {
  guid: string;
  relPath: string;
  absPath: string;
  source: ResourceSource;
  sizeBytes: number;
  exists: boolean;
}

// ── Pure helpers ─────────────────────────────────────────────────────────────

export function formatScript(input: {
  candidates: RemovalCandidate[];
  shell: "bash" | "powershell" | "cmd";
}): string {
  const { candidates, shell } = input;
  if (candidates.length === 0) {
    return "# No unused resources found — nothing to remove.";
  }
  const lines: string[] = [];
  const totalBytes = candidates.reduce((n, c) => n + c.sizeBytes, 0);
  switch (shell) {
    case "bash": {
      lines.push("#!/usr/bin/env bash");
      lines.push("# refactor_remove_unused — generated by Enfusion MCP");
      lines.push(`# ${candidates.length} files, ${formatBytes(totalBytes)} total`);
      lines.push("# REVIEW EACH LINE BEFORE EXECUTING.");
      lines.push("set -euo pipefail");
      lines.push("");
      for (const c of candidates) {
        // Not-on-disk entries are emitted as comment-only lines so they can
        // never execute (M12).
        if (!c.exists) {
          lines.push(`# NOT ON DISK (skipped): "${c.absPath}"  {${c.guid}} [${c.source}]`);
          continue;
        }
        lines.push(`rm -v "${c.absPath}"  # {${c.guid}} [${c.source}]`);
      }
      break;
    }
    case "powershell": {
      lines.push("# refactor_remove_unused — generated by Enfusion MCP");
      lines.push(`# ${candidates.length} files, ${formatBytes(totalBytes)} total`);
      lines.push("# REVIEW EACH LINE BEFORE EXECUTING.");
      lines.push("$ErrorActionPreference = 'Stop'");
      lines.push("");
      for (const c of candidates) {
        if (!c.exists) {
          lines.push(`# NOT ON DISK (skipped): "${c.absPath}"  {${c.guid}} [${c.source}]`);
          continue;
        }
        lines.push(`Remove-Item -Path "${c.absPath}" -Verbose  # {${c.guid}} [${c.source}]`);
      }
      break;
    }
    case "cmd": {
      lines.push("@echo off");
      lines.push("REM refactor_remove_unused — generated by Enfusion MCP");
      lines.push(`REM ${candidates.length} files, ${formatBytes(totalBytes)} total`);
      lines.push("REM REVIEW EACH LINE BEFORE EXECUTING.");
      lines.push("");
      for (const c of candidates) {
        // cmd has no trailing-comment syntax: `REM` after a command is just
        // more arguments to `del`. Comments go on their OWN line (M12).
        if (!c.exists) {
          lines.push(`REM NOT ON DISK (skipped): "${c.absPath}"  {${c.guid}} [${c.source}]`);
          continue;
        }
        lines.push(`REM {${c.guid}} [${c.source}]`);
        lines.push(`del /F "${c.absPath}"`);
      }
      break;
    }
  }
  return lines.join("\n");
}

function formatBytes(b: number): string {
  if (b < 1024) return `${b} B`;
  const kb = b / 1024;
  if (kb < 1024) return `${kb.toFixed(1)} KB`;
  const mb = kb / 1024;
  return `${mb.toFixed(2)} MB`;
}

export function formatReport(input: {
  candidates: RemovalCandidate[];
  shell: "bash" | "powershell" | "cmd";
  script: string;
  source: ResourceSource | "*";
}): string {
  const { candidates, shell, script, source } = input;
  const lines: string[] = [];
  const filterSuffix = source !== "*" ? ` [source=${source}]` : "";
  lines.push(`## refactor_remove_unused — dry-run plan${filterSuffix}`);
  lines.push("");
  if (candidates.length === 0) {
    lines.push("No unused resources to remove. Nothing to do.");
    return lines.join("\n");
  }
  const totalBytes = candidates.reduce((n, c) => n + c.sizeBytes, 0);
  const missing = candidates.filter((c) => !c.exists).length;
  lines.push(
    `Found **${candidates.length}** unused resource${candidates.length !== 1 ? "s" : ""} (${formatBytes(totalBytes)} total).`,
  );
  if (missing > 0) {
    lines.push(
      `⚠ ${missing} candidate${missing !== 1 ? "s" : ""} flagged as not-on-disk — the index references files that no longer exist. Listed in the script as comment-only lines (they will not execute); re-crawl the project to drop them from the index.`,
    );
  }
  lines.push("");
  lines.push("⚠ **DRY-RUN ONLY.** Live-delete is intentionally not provided at L5.");
  lines.push("Review every line of the script below before executing it.");
  lines.push("");
  lines.push(`### Removal script (${shell})`);
  lines.push("");
  lines.push("```" + (shell === "powershell" ? "powershell" : shell === "cmd" ? "bat" : "bash"));
  lines.push(script);
  lines.push("```");
  lines.push("");
  lines.push(
    "If a resource is unused in your project-index but **referenced from a workshop mod you depend on**, removing it will break that dep. Cross-check with `find_references` against any GUID you're suspicious of before running the script.",
  );
  return lines.join("\n");
}

// ── Registration ─────────────────────────────────────────────────────────────

export function registerRefactorRemoveUnused(
  server: McpServer,
  index: ProjectIndex,
): void {
  server.registerTool(
    "refactor_remove_unused",
    {
      description:
        "Emit an executable removal script for resources with zero inbound references. " +
        "DRY-RUN ONLY at v1 — the tool returns a shell/PowerShell/cmd script for the human to review and execute by hand. " +
        "Live-delete is intentionally NOT provided to prevent LLM-induced data loss. " +
        "Composes with `find_unused_resources` for the underlying query.",
      inputSchema: {
        source: z
          .enum(["user", "core", "workshop"])
          .optional()
          .describe("Filter — almost always `user` (you don't want to delete core or workshop content)"),
        shell: z
          .enum(["bash", "powershell", "cmd"])
          .default("powershell")
          .describe("Shell flavor for the emitted script"),
        limit: z
          .number()
          .min(1)
          .max(1000)
          .default(500)
          .describe("Max candidates to include in the script (default 500)"),
      },
    },
    async ({ source, shell, limit }) => {
      try {
        const result = index.findUnusedResources({ source, limit, offset: 0 });
        const candidates: RemovalCandidate[] = [];
        for (const row of result.rows) {
          // Resource file_path is relative to its owning project's root_path,
          // so it's useless verbatim (neither absolute nor reliably
          // CWD-relative). Resolve against the owning project's root via the
          // schema-v2 project_id FK (RBE-8). Fall back to the bare file_path
          // only when the row has no owning project (NULL project_id).
          let exists = false;
          let sizeBytes = 0;
          const resolved = index.resolveAbsPathByGuid(row.guid);
          const absPath = resolved ?? row.file_path;
          if (existsSync(absPath)) {
            try {
              sizeBytes = statSync(absPath).size;
              exists = true;
            } catch {
              /* skip */
            }
          }
          candidates.push({
            guid: row.guid,
            relPath: row.file_path,
            absPath,
            source: row.source,
            sizeBytes,
            exists,
          });
        }
        const script = formatScript({ candidates, shell });
        const text = formatReport({
          candidates,
          shell,
          script,
          source: source ?? "*",
        });
        return { content: [{ type: "text" as const, text }] };
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        return {
          content: [{ type: "text" as const, text: `Error generating removal script: ${msg}` }],
          isError: true,
        };
      }
    },
  );
}

// Internal helper referenced by tests if needed.
void resolve;
